### ISSUE TITLE
App: audio not loading into editor

### ISSUE THREAD

**Issue by labettis** [ingenology/cosmix#2]
When clicking on an audio track, no response and doesn't add into editor. In console, error message:

```
''webkitAudioContext' is deprecated. Please use 'AudioContext' instead.
Views.TrackPicker.js:127 Uncaught TypeError: this.uploadFile is not a function(anonymous function) @ Views.TrackPicker.js:127(anonymous function) @ filer.min.js:11
```

![screen shot 2015-04-17 at 6 54 47 pm](https://cloud.githubusercontent.com/assets/7086279/7212866/140925a4-e534-11e4-8f80-c5b27d5e87e0.png)

DomMonster report shows a little more:

```
Uncaught TypeError: this.uploadFile is not a function(anonymous function) @ Views.TrackPicker.js:127(anonymous function) @ filer.min.js:11
```

**Comment by dniccum** [comment]
This issue was fixed in the [following commit](https://github.com/ingenology/cosmix/commit/9316788b9295933890c0592663a969361eae47db).
